/* ===================================================================
   KORE LEGION — agent data
   Drives the agent cards and the detail drawer.
   =================================================================== */

window.KORE_AGENTS = [
  {
    key: "vera",
    name: "Vera",
    role: "Chief of Staff",
    color: "#e0b53d",
    glow: "rgba(224,181,61,0.16)",
    tag: "The one running everything before you even wake up.",
    tagline: "Vera doesn't sleep. Neither does your life.",
    intro: "Your morning briefing hits before you open your eyes — schedule, priorities, alerts, everything you need to know about the day, delivered automatically. Vera coordinates every agent, monitors your wellness, and makes sure the right people are always in the loop.",
    does: [
      "Handles things end to end — calls people, books reservations, and schedules around your calendar, all on your behalf",
      "Negotiates times and details for you, makes the judgment calls, and follows up so you don't have to",
      "Daily morning briefing — schedule, priorities, what matters today",
      "Wellness monitoring — checks in when you've gone quiet",
      "Coordinates all agents so they work as one system",
      "Makes live voice calls and sends texts to your contacts when something's wrong",
      "Briefs Claude and Grok automatically — so any AI you talk to is always up to date",
      "Learns who you are and speaks on your behalf when it matters",
    ],
  },
  {
    key: "shield",
    name: "Shield",
    role: "Legal Intelligence",
    color: "#4a90d9",
    glow: "rgba(74,144,217,0.16)",
    tag: "Silent until you need it. Then it moves faster than you can.",
    tagline: "Your lawyer walks in ready. Not catching up.",
    intro: "Most people don't have legal protection until after something goes wrong. Shield changes that. The moment you say you're being pulled over, it calls you and guides you through every second — and it monitors your cases, tracks your court dates, and stays connected to your attorney so the right people always know.",
    does: [
      "Pulled over? Tell Shield. It calls you in seconds and walks you through the stop — what to say, what not to say, your exact rights, in real time",
      "Records the entire encounter and sends the transcript straight to your attorney as it happens",
      "Monitors active cases and court dates automatically",
      "Sends your attorney a complete legal briefing the moment something critical happens",
      "Activates arrest mode — lawyer notified, family notified, bail monitored within 5 minutes",
      "Makes live calls and sends texts and emails to your attorney and family instantly",
      "Scans court records daily — so nothing falls through the cracks",
      "Alerts you when fees or deadlines are approaching",
      "Notifies your family with enough information to actually help",
    ],
  },
  {
    key: "ledger",
    name: "Ledger",
    role: "Personal Finance",
    color: "#1d9e75",
    glow: "rgba(29,158,117,0.16)",
    tag: "Knows your numbers better than you do.",
    tagline: "On payday you get a text. Priority order. Exact amounts. No guessing.",
    intro: "You should never be surprised by your own money. Ledger tracks everything — income, bills, investments, crypto — and tells you exactly what to do with your money before you touch it.",
    does: [
      "Bank integration — reads your actual transactions in real time",
      "Tracks income, expenses, and accounts automatically",
      "Alerts you before bills are due — not after",
      "Monitors investments, trading P&L, and crypto balances",
      "Sends a payday brief — priority order, exact amounts, where it goes first",
      "Flags unusual spending, overdue payments, and financial risks",
      "Weekly finance report every Sunday — the full picture of where you stand",
    ],
  },
  {
    key: "haven",
    name: "Haven",
    role: "Health & Performance",
    color: "#639922",
    glow: "rgba(99,153,34,0.16)",
    tag: "An elite personal trainer who never cancels and always knows your data.",
    tagline: "Haven programs you like an athlete. Because that's what you are.",
    intro: "Haven doesn't send generic workout tips. It designs your actual program, checks in every morning, and adjusts based on how you're really recovering. No wearable required — just honest daily check-ins and a system that actually pays attention.",
    does: [
      "Designs your weekly training program — exercises, sets, reps, rest periods",
      "Morning check-in every day with exactly what's on the schedule",
      "Evening text — did you train, how'd you sleep, energy level 1–10",
      "Tracks recovery and sleep quality, flags when you need to pull back",
      "Integrates sauna and recovery as part of the program, not an afterthought",
      "Pattern analysis — finds real correlations in your data over time",
      "Calls out when you're slipping — once, directly, then moves forward",
    ],
  },
  {
    key: "echo",
    name: "Echo",
    role: "Accountability & Tasks",
    color: "#ba7517",
    glow: "rgba(186,117,23,0.16)",
    tag: "The one who remembers everything you said you'd do.",
    tagline: "Echo doesn't care about excuses. Just results.",
    intro: "Echo doesn't motivate. It tracks. Every commitment you make, every task that comes out of every agent conversation — Echo logs it, follows up on it, and doesn't let it disappear. Nothing slips through.",
    does: [
      "Tracks every commitment and task automatically",
      "Pulls action items from every other agent's activity — nothing gets lost",
      "Follows up when things aren't done — no guilt trips, just facts",
      "Tracks habits and streaks over time",
      "Daily check-in every morning — what's open, what's due, what's done",
      "Weekly wins recap every Sunday — what actually got done, what moved forward",
    ],
  },
  {
    key: "rex",
    name: "Rex",
    role: "Work Assistant",
    color: "#d4537e",
    glow: "rgba(212,83,126,0.16)",
    tag: "The sharp colleague who's always ready and knows how the game works.",
    tagline: "Rex doesn't theorize. It gives you the move.",
    intro: "Rex doesn't give you options. It gives you the move. Whether you need an email drafted, a meeting prepped, a job found, or someone to tell you straight that what you're about to do is a bad idea — Rex is that voice.",
    does: [
      "Drafts professional emails and messages on command",
      "Preps you for meetings, presentations, and tough conversations",
      "Thinks through workplace situations and tells you exactly what to do",
      "Writes and tailors your resume for each role you apply to",
      "Scans job boards for roles that match your skills and goals",
      "Drafts and sends job applications on your behalf, then follows up",
      "Calls out bad moves before you make them",
      "Monday morning check-in to start the week right",
    ],
  },
];
