services:
  - type: web
    name: korelegion-site
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /optin.html
        destination: /optin.html
      - type: rewrite
        source: /privacy.html
        destination: /privacy.html
      - type: rewrite
        source: /terms.html
        destination: /terms.html
      - type: rewrite
        source: /*
        destination: /index.html
